apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-todo
spec:
  destination:
    name: ''
    namespace: argo
    server: 'https://kubernetes.default.svc'
  source:
    path: infra-apps
    repoURL: 'https://github.com/PhantomPixelist/protfolio_gitops' # Change to ssh
    targetRevision: digial_ocean  # Change back to HEAD to master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
