
# name for labels and deployment
name: "todoapp"

# replicas is the number of replicas for the deployment
replicas: 3

# port for application
port: '5000' #application is running on port 5000

image:
  name: elior1001/protolio-todo
  tag: 1.0.2

imagePullSecret: "regcred"

# DB_URL to pass to deployment should be base 64 encoded then it will be a sealed secret
# a one option to pass the url
sealedsecret:
  enabled: true
  db_url: "AgA2r848/PJueWjfjAzLUDX6s6dWDvKqU5pffmA4AM6qJjcOLjKWGPgnphbumUgFj+rw2dPtTeO4kuJE1stMtsc8iq22ITAP5Aeqxt3sECCimJNJkz6w4SxX9y6EnnCjfFkOlSIMxyqA2KfbgrfCDFEl5gXZ+C289y2zfZWLhOqNKQY9aFwIZiBKUZqiN0scVl1gqJZlYfYNHDylSsKlqy1LXHP8LjEhzSQr02GiCWDJBSAPV/oLJvl41z5Bf9NgGSP8VG3qwtIsr1Y12EFW3uig1hSNKHuimXSjhhkLvEcrpLmsy6IV5tfHR4C9sFjozO87RpTkRx4xg3eAyoXus+SWIL+tjCcBEjjBvL8O58KIf8I4IsjRF3FIYEMSbwIB329GeSl2jz3Jmf1nmHaUgTKdeH/eFJM8jQdIH/zYr2CyOgzvwYOMLSqUF16/0/d/sxeb+cRoc/ZqrgNWNJOBLpF+UybQQscN8UWCYi3QDAZ6x3XVLuQwUWHPF24iM1vx3fDvh/nyfkQ88Pxtxk6IYDKPaRTRKIWTOMJmFC2K2VKAd8hEgo5LjYBG3oNag5k+H4cX+zLNMe6EEqPwPbAuAwk70D8mg+hCH6HXRmirlhGJ9s606k3BQ2kpi8N2se4rs2YPfFmHnObBfOpbd0FCmCPm6pC3o2bqgS/Wy+rLtTAZW9JKa55CjAUfrJUGl0V15I5Pn/UCPdBDiGhdE7oc46yE54JJ0EEqyg9WkuAbRw2EijK/eG/6dadiUDk="

# if sealedsecret disabled pass a base 64 url to the mongodb
# db_url: bW9uZ29kYjovL3Jvb3Q6cm9vdEBtb25nby1tb25nb2RiLWhlYWRsZXNz
db_url: ""

# mongo db Values must be declared so the apllication will be connect to the db
mongodb:
  # FullnameOverride is the prefix for all services and resources that will be created by the mongo sub-chart
  fullnameOverride: "mongo-mongodb"
  auth:
    # Database credenditals 
    #rootUser: root
    #rootPassword: "root"
    # Existing secret name with MongoDB(&reg;) credentials (keys: `mongodb-passwords`, `mongodb-root-password`, `mongodb-metrics-password`, ` mongodb-replica-set-key`)
    existingSecret: "dbcred"
  persistence:
    size: 2Gi

# Configuration about ingress
ingress:
  enabled: true 
  # tls means wether to deploy with a tls certificate or not
  tls: true
  # wether to use staging cerficiate or production cluster issuer if false set to production.
  prod: false
  # host is the dns for the ingress
  host: taskmaster.site
  # ingress_class the class name for the ingress
  ingress_class: "nginx"
  # Cluster issuer mail only if tls is enabled
  email: "elior1001@gmail.com"


# Configuration about kibana dashboard:
kibana:
  # enable the job to load kibana dashboard
  enabled: true
  # make sure it exists in the logging namespace
  serviceName: elastic-search-kibana
  port: 5601
  index_pattern: |
    {"attributes":{"fieldAttrs":"{\"kubernetes.pod_ip\":{\"count\":3},\"method\":{\"count\":5},\"protocol\":{\"count\":2},\"referer\":{\"count\":1},\"response_status\":{\"count\":5}}","fieldFormatMap":"{}","fields":"[]","name":"logstlogstash-todoash","runtimeFieldMap":"{}","sourceFilters":"[]","timeFieldName":"@timestamp","title":"logstash-todo","typeMeta":"{}"},"coreMigrationVersion":"8.6.0","created_at":"2023-02-15T18:27:39.901Z","id":"37a569d0-ed03-4b81-8ec5-5f0e750a1f30","migrationVersion":{"index-pattern":"8.0.0"},"references":[],"type":"index-pattern","updated_at":"2023-02-15T18:27:39.901Z","version":"WzI2LDFd"}
    {"excludedObjects":[],"excludedObjectsCount":0,"exportedCount":1,"missingRefCount":0,"missingReferences":[]}
  kibana_dashboard: |
    {
      "version": "8.6.0",
      "objects": [
        {
          "id": "2ae51870-ac58-11ed-ac40-1fd1637ce8ec",
          "type": "dashboard",
          "namespaces": [
            "default"
          ],
          "updated_at": "2023-02-15T18:52:40.765Z",
          "created_at": "2023-02-15T18:52:40.765Z",
          "version": "WzQzNSwxXQ==",
          "attributes": {
            "controlGroupInput": {
              "controlStyle": "oneLine",
              "chainingSystem": "HIERARCHICAL",
              "panelsJSON": "{\"e1d9c467-dcc4-4a23-bfb0-871b7322e697\":{\"order\":0,\"width\":\"medium\",\"grow\":true,\"type\":\"rangeSliderControl\",\"explicitInput\":{\"fieldName\":\"response_status\",\"title\":\"response_status\",\"id\":\"e1d9c467-dcc4-4a23-bfb0-871b7322e697\",\"enhancements\":{}}}}",
              "ignoreParentSettingsJSON": "{\"ignoreFilters\":false,\"ignoreQuery\":false,\"ignoreTimerange\":false,\"ignoreValidations\":false}"
            },
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[]}"
            },
            "timeRestore": false,
            "optionsJSON": "{\"useMargins\":true,\"syncColors\":false,\"syncCursor\":true,\"syncTooltips\":false,\"hidePanelTitles\":false}",
            "description": "logs_of_the_application",
            "panelsJSON": "[{\"version\":\"8.6.0\",\"type\":\"lens\",\"gridData\":{\"x\":0,\"y\":15,\"w\":24,\"h\":15,\"i\":\"20eef1da-238a-4d7a-83db-c496a30c21e1\"},\"panelIndex\":\"20eef1da-238a-4d7a-83db-c496a30c21e1\",\"embeddableConfig\":{\"attributes\":{\"title\":\"Requests\",\"description\":\"\",\"visualizationType\":\"lnsPie\",\"type\":\"lens\",\"references\":[{\"type\":\"index-pattern\",\"id\":\"37a569d0-ed03-4b81-8ec5-5f0e750a1f30\",\"name\":\"indexpattern-datasource-layer-8478fc35-c2c0-4312-9e14-f0d653d8a5a6\"}],\"state\":{\"visualization\":{\"shape\":\"donut\",\"layers\":[{\"layerId\":\"8478fc35-c2c0-4312-9e14-f0d653d8a5a6\",\"primaryGroups\":[\"13c8fbbc-554c-4ce5-aa2d-a5bc4315b3fe\"],\"metrics\":[\"7423b727-3e93-4f23-aaf2-fff25e59bba8\"],\"numberDisplay\":\"percent\",\"categoryDisplay\":\"default\",\"legendDisplay\":\"default\",\"nestedLegend\":false,\"layerType\":\"data\"}]},\"query\":{\"language\":\"kuery\",\"query\":\"request: *\"},\"filters\":[],\"datasourceStates\":{\"formBased\":{\"layers\":{\"8478fc35-c2c0-4312-9e14-f0d653d8a5a6\":{\"columns\":{\"13c8fbbc-554c-4ce5-aa2d-a5bc4315b3fe\":{\"label\":\"Top 5 values of response_status\",\"dataType\":\"number\",\"operationType\":\"terms\",\"scale\":\"ordinal\",\"sourceField\":\"response_status\",\"isBucketed\":true,\"params\":{\"size\":5,\"orderBy\":{\"type\":\"column\",\"columnId\":\"7423b727-3e93-4f23-aaf2-fff25e59bba8\"},\"orderDirection\":\"desc\",\"otherBucket\":true,\"missingBucket\":false,\"parentFormat\":{\"id\":\"terms\"},\"include\":[],\"exclude\":[],\"includeIsRegex\":false,\"excludeIsRegex\":false}},\"7423b727-3e93-4f23-aaf2-fff25e59bba8\":{\"label\":\"Median of response_status\",\"dataType\":\"number\",\"operationType\":\"median\",\"sourceField\":\"response_status\",\"isBucketed\":false,\"scale\":\"ratio\",\"params\":{\"emptyAsNull\":true}}},\"columnOrder\":[\"13c8fbbc-554c-4ce5-aa2d-a5bc4315b3fe\",\"7423b727-3e93-4f23-aaf2-fff25e59bba8\"],\"incompleteColumns\":{},\"sampling\":1}}},\"textBased\":{\"layers\":{}}},\"internalReferences\":[],\"adHocDataViews\":{}}},\"enhancements\":{}}},{\"version\":\"8.6.0\",\"type\":\"lens\",\"gridData\":{\"x\":24,\"y\":0,\"w\":24,\"h\":15,\"i\":\"2931d6f3-4ee7-49ba-bd8a-159320d8ba2a\"},\"panelIndex\":\"2931d6f3-4ee7-49ba-bd8a-159320d8ba2a\",\"embeddableConfig\":{\"attributes\":{\"title\":\"count of request to api endpoint\",\"description\":\"\",\"visualizationType\":\"lnsMetric\",\"type\":\"lens\",\"references\":[{\"type\":\"index-pattern\",\"id\":\"37a569d0-ed03-4b81-8ec5-5f0e750a1f30\",\"name\":\"indexpattern-datasource-layer-d3a8557e-348e-4dd6-89ac-63c86b88d7f3\"}],\"state\":{\"visualization\":{\"layerId\":\"d3a8557e-348e-4dd6-89ac-63c86b88d7f3\",\"layerType\":\"data\",\"metricAccessor\":\"e7b3c9e0-6857-403f-83aa-8dd1d9d4b972\",\"breakdownByAccessor\":\"cc222565-16e8-4d61-96b5-2188058bc380\",\"palette\":{\"type\":\"palette\",\"name\":\"status\",\"params\":{\"name\":\"status\",\"reverse\":false,\"rangeType\":\"percent\",\"rangeMin\":0,\"rangeMax\":100,\"progression\":\"fixed\",\"stops\":[{\"color\":\"#209280\",\"stop\":33.33},{\"color\":\"#d6bf57\",\"stop\":66.66},{\"color\":\"#cc5642\",\"stop\":100}],\"steps\":3,\"colorStops\":[],\"continuity\":\"all\",\"maxSteps\":5}}},\"query\":{\"query\":\"request: *\",\"language\":\"kuery\"},\"filters\":[],\"datasourceStates\":{\"formBased\":{\"layers\":{\"d3a8557e-348e-4dd6-89ac-63c86b88d7f3\":{\"columns\":{\"cc222565-16e8-4d61-96b5-2188058bc380\":{\"label\":\"Top 5 values of request.keyword\",\"dataType\":\"string\",\"operationType\":\"terms\",\"scale\":\"ordinal\",\"sourceField\":\"request.keyword\",\"isBucketed\":true,\"params\":{\"size\":5,\"orderBy\":{\"type\":\"column\",\"columnId\":\"e7b3c9e0-6857-403f-83aa-8dd1d9d4b972\"},\"orderDirection\":\"desc\",\"otherBucket\":true,\"missingBucket\":false,\"parentFormat\":{\"id\":\"terms\"},\"include\":[],\"exclude\":[],\"includeIsRegex\":false,\"excludeIsRegex\":false}},\"e7b3c9e0-6857-403f-83aa-8dd1d9d4b972\":{\"label\":\"Count of records\",\"dataType\":\"number\",\"operationType\":\"count\",\"isBucketed\":false,\"scale\":\"ratio\",\"sourceField\":\"___records___\",\"params\":{\"emptyAsNull\":true}}},\"columnOrder\":[\"cc222565-16e8-4d61-96b5-2188058bc380\",\"e7b3c9e0-6857-403f-83aa-8dd1d9d4b972\"],\"incompleteColumns\":{},\"sampling\":1}}},\"textBased\":{\"layers\":{}}},\"internalReferences\":[],\"adHocDataViews\":{}}},\"enhancements\":{},\"hidePanelTitles\":false},\"title\":\"reurestCount\"},{\"version\":\"8.6.0\",\"type\":\"lens\",\"gridData\":{\"x\":0,\"y\":0,\"w\":24,\"h\":15,\"i\":\"ffc2328a-666f-48c4-ac9b-a2ed2c9303b7\"},\"panelIndex\":\"ffc2328a-666f-48c4-ac9b-a2ed2c9303b7\",\"embeddableConfig\":{\"attributes\":{\"title\":\"request_precentage\",\"description\":\"\",\"visualizationType\":\"lnsPie\",\"type\":\"lens\",\"references\":[{\"type\":\"index-pattern\",\"id\":\"37a569d0-ed03-4b81-8ec5-5f0e750a1f30\",\"name\":\"indexpattern-datasource-layer-27f9c85e-ddb0-41e0-a928-422e3c82c90c\"}],\"state\":{\"visualization\":{\"shape\":\"donut\",\"layers\":[{\"layerId\":\"27f9c85e-ddb0-41e0-a928-422e3c82c90c\",\"primaryGroups\":[\"c067f0b0-0ba9-4fd3-a169-cf97d8a15111\"],\"metrics\":[\"b1727792-1594-43cb-a672-c73ad53c3b0e\"],\"numberDisplay\":\"percent\",\"categoryDisplay\":\"default\",\"legendDisplay\":\"default\",\"nestedLegend\":false,\"layerType\":\"data\"}]},\"query\":{\"language\":\"kuery\",\"query\":\"method.keyword : *\"},\"filters\":[],\"datasourceStates\":{\"formBased\":{\"layers\":{\"27f9c85e-ddb0-41e0-a928-422e3c82c90c\":{\"columns\":{\"c067f0b0-0ba9-4fd3-a169-cf97d8a15111\":{\"label\":\"Top 5 values of method.keyword\",\"dataType\":\"string\",\"operationType\":\"terms\",\"scale\":\"ordinal\",\"sourceField\":\"method.keyword\",\"isBucketed\":true,\"params\":{\"size\":5,\"orderBy\":{\"type\":\"column\",\"columnId\":\"b1727792-1594-43cb-a672-c73ad53c3b0e\"},\"orderDirection\":\"desc\",\"otherBucket\":true,\"missingBucket\":false,\"parentFormat\":{\"id\":\"terms\"},\"include\":[],\"exclude\":[],\"includeIsRegex\":false,\"excludeIsRegex\":false}},\"b1727792-1594-43cb-a672-c73ad53c3b0e\":{\"label\":\"Count of records\",\"dataType\":\"number\",\"operationType\":\"count\",\"isBucketed\":false,\"scale\":\"ratio\",\"sourceField\":\"___records___\",\"params\":{\"emptyAsNull\":true}}},\"columnOrder\":[\"c067f0b0-0ba9-4fd3-a169-cf97d8a15111\",\"b1727792-1594-43cb-a672-c73ad53c3b0e\"],\"incompleteColumns\":{},\"sampling\":1}}},\"textBased\":{\"layers\":{}}},\"internalReferences\":[],\"adHocDataViews\":{}}},\"enhancements\":{}}}]",
            "title": "todologs",
            "version": 1
          },
          "references": [
            {
              "type": "index-pattern",
              "id": "37a569d0-ed03-4b81-8ec5-5f0e750a1f30",
              "name": "20eef1da-238a-4d7a-83db-c496a30c21e1:indexpattern-datasource-layer-8478fc35-c2c0-4312-9e14-f0d653d8a5a6"
            },
            {
              "type": "index-pattern",
              "id": "37a569d0-ed03-4b81-8ec5-5f0e750a1f30",
              "name": "2931d6f3-4ee7-49ba-bd8a-159320d8ba2a:indexpattern-datasource-layer-d3a8557e-348e-4dd6-89ac-63c86b88d7f3"
            },
            {
              "type": "index-pattern",
              "id": "37a569d0-ed03-4b81-8ec5-5f0e750a1f30",
              "name": "ffc2328a-666f-48c4-ac9b-a2ed2c9303b7:indexpattern-datasource-layer-27f9c85e-ddb0-41e0-a928-422e3c82c90c"
            },
            {
              "name": "controlGroup_e1d9c467-dcc4-4a23-bfb0-871b7322e697:rangeSliderDataView",
              "type": "index-pattern",
              "id": "37a569d0-ed03-4b81-8ec5-5f0e750a1f30"
            }
          ],
          "migrationVersion": {
            "dashboard": "8.6.0"
          },
          "coreMigrationVersion": "8.6.0"
        },
        {
          "id": "37a569d0-ed03-4b81-8ec5-5f0e750a1f30",
          "type": "index-pattern",
          "namespaces": [
            "default"
          ],
          "updated_at": "2023-02-15T18:27:39.901Z",
          "created_at": "2023-02-15T18:27:39.901Z",
          "version": "WzI2LDFd",
          "attributes": {
            "fieldAttrs": "{\"kubernetes.pod_ip\":{\"count\":3},\"method\":{\"count\":5},\"protocol\":{\"count\":2},\"referer\":{\"count\":1},\"response_status\":{\"count\":5}}",
            "fieldFormatMap": "{}",
            "fields": "[]",
            "name": "logstlogstash-todoash",
            "runtimeFieldMap": "{}",
            "sourceFilters": "[]",
            "timeFieldName": "@timestamp",
            "title": "logstash-todo",
            "typeMeta": "{}"
          },
          "references": [],
          "migrationVersion": {
            "index-pattern": "8.0.0"
          },
          "coreMigrationVersion": "8.6.0"
        }
      ]
    }

# Configuration about grafana alerts
grafana: 
  # enable the job to load alerts and contacts point
  enabled: true
  # make sure it exists in the monitoring namespace
  serviceName: grafana
  port: 80
  alert_1: |
    {"id":1,"uid":"8oIQIA14k","orgID":1,"folderUID":"GnjUIAJVz","ruleGroup":"ops","title":"High Memory Usage in nodes","condition":"C","data":[{"refId":"A","queryType":"","relativeTimeRange":{"from":21600,"to":0},"datasourceUid":"PBFA97CFB590B2093","model":{"datasource":{"type":"prometheus","uid":"PBFA97CFB590B2093"},"editorMode":"code","expr":"(node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / (node_memory_MemTotal_bytes) * 100 ","interval":"","intervalMs":15000,"legendFormat":"__auto","maxDataPoints":43200,"range":true,"refId":"A"}},{"refId":"B","queryType":"","relativeTimeRange":{"from":21600,"to":0},"datasourceUid":"-100","model":{"conditions":[{"evaluator":{"params":[],"type":"gt"},"operator":{"type":"and"},"query":{"params":["B"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"-100"},"expression":"A","hide":false,"intervalMs":1000,"maxDataPoints":43200,"reducer":"last","refId":"B","type":"reduce"}},{"refId":"C","queryType":"","relativeTimeRange":{"from":21600,"to":0},"datasourceUid":"-100","model":{"conditions":[{"evaluator":{"params":[75],"type":"gt"},"operator":{"type":"and"},"query":{"params":["C"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"-100"},"expression":"B","hide":false,"intervalMs":1000,"maxDataPoints":43200,"refId":"C","type":"threshold"}}],"updated":"2023-02-16T16:09:23Z","noDataState":"NoData","execErrState":"Error","for":"5m","annotations":{"__dashboardUid__":"-FKhqTJ4z","__panelId__":"2"}}
  alert_2: |
    {"id":2,"uid":"za_6IA14z","orgID":1,"folderUID":"GnjUIAJVz","ruleGroup":"ops","title":"Pod Isnt Ready","condition":"C","data":[{"refId":"A","queryType":"","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"PBFA97CFB590B2093","model":{"editorMode":"code","expr":"sum by (namespace) (kube_pod_status_ready{condition=\"false\"})","hide":false,"intervalMs":1000,"legendFormat":"__auto","maxDataPoints":43200,"range":true,"refId":"A"}},{"refId":"B","queryType":"","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"-100","model":{"conditions":[{"evaluator":{"params":[],"type":"gt"},"operator":{"type":"and"},"query":{"params":["B"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"-100"},"expression":"A","hide":false,"intervalMs":1000,"maxDataPoints":43200,"reducer":"last","refId":"B","type":"reduce"}},{"refId":"C","queryType":"","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"-100","model":{"conditions":[{"evaluator":{"params":[1],"type":"gt"},"operator":{"type":"and"},"query":{"params":["C"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"-100"},"expression":"B","hide":false,"intervalMs":1000,"maxDataPoints":43200,"refId":"C","type":"threshold"}}],"updated":"2023-02-16T16:09:23Z","noDataState":"NoData","execErrState":"Error","for":"5m","annotations":{"summary":"pod is not  in the ready state"}}
  alert_3: | 
    {"id":3,"uid":"8hCkH014k","orgID":1,"folderUID":"GnjUIAJVz","ruleGroup":"ops","title":"High Cpu Usage","condition":"C","data":[{"refId":"A","queryType":"","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"PBFA97CFB590B2093","model":{"editorMode":"code","expr":"(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[2m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total[2m])))) * 100","hide":false,"intervalMs":1000,"legendFormat":"__auto","maxDataPoints":43200,"range":true,"refId":"A"}},{"refId":"B","queryType":"","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"-100","model":{"conditions":[{"evaluator":{"params":[],"type":"gt"},"operator":{"type":"and"},"query":{"params":["B"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"-100"},"expression":"A","hide":false,"intervalMs":1000,"maxDataPoints":43200,"reducer":"last","refId":"B","type":"reduce"}},{"refId":"C","queryType":"","relativeTimeRange":{"from":600,"to":0},"datasourceUid":"-100","model":{"conditions":[{"evaluator":{"params":[10],"type":"gt"},"operator":{"type":"and"},"query":{"params":["C"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"datasource":{"type":"__expr__","uid":"-100"},"expression":"B","hide":false,"intervalMs":1000,"maxDataPoints":43200,"refId":"C","type":"threshold"}}],"updated":"2023-02-16T16:09:23Z","noDataState":"NoData","execErrState":"Error","for":"5m","annotations":{"summary":"Cpu Is Below 10%"}}
  folder: |
    {
        "uid": "GnjUIAJVz",
        "title": "Application-Alerts"
    }    
  # contact_point: |
  #   {"uid":"oDHTD01Vk","name":"slack-alert-channel","type":"slack","settings":{"url":"https://hooks.slack.com/services/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"},"disableResolveMessage":false}

  contact_point: |
    {"uid":"oDHTD01Vk","name":"slack-alert-channel","type":"slack","settings":{"url":"SECURE"},"disableResolveMessage":false}
  contact_policy: |
    {"receiver":"slack-alert-channel","group_by":["grafana_folder","alertname"]}



#Requests and limits for deployment
resources:
  requests:
    memory: "16Mi"
    cpu: "125m"
  limits:
    memory: "128Mi"
    cpu: "500m"

