
# name for labels and deployment
name: "todoapp"

# replicas is the number of replicas for the deployment
replicas: 3

# port for application
port: '5000' #application is running on port 5000

image:
  name: elior1001/protolio-todo
  tag: 1.1.47

imagePullSecret: "regcred"

# DB_URL to pass to deployment should be base 64 encoded then it will be a sealed secret
# a one option to pass the url
sealedsecret:
  enabled: true
  db_url: "AgDB1sDCxWslW4Jm+Mp92hKPCaUkafR5ei7cb0UYwYlQDeu8OEe4KWK44/qTUeUlVUNuyW8VoNXU4Et9mxh3J8z6Tc43a0G4l2+WA4CjW7sY2K02bi7tZl+m0NAzWhcX91CA0xtUzWslOH1f6hlnyF6a9vbjWfeJ3fI6/OA2xZ39hgmIcGJ2CMdbGgbKnhNotBDAXPE9urWzwagAwzaj6nanYz9rZyqzhc7YQypBLzjRbLdTi2kAl7+sCsP9ayAgPJdcfE+zZ16EgZuJVhOZpA2OIxC0KCANMWRM2Muz3XZb9yAp4EBxo0b+0eh7km+DmZmiGJAiXhk9iNeB7OQ5NYEEdAztoY7mWk2J+YxTsooUQgbpoNkvP+Hse6RvI+uO6NNlkFUZKIuHbMb0eydZhgx+VLNE6EOsNqfilVvatYyPkUS53tm0VR6XFA0AZWZel4MchfsrVRnvgn6dGuGVeync+MLd8r7zNQXayZXHbwJ0S4hvoZjcd7BAWvB5NNhzHfWFuXI1G38AepE0y26vfVFyPFiXeAgPzrYP5tKi2Dcpi1OXbM81G9hW8ZyFBSBn4pM4iD7WieMSgYfuqKhIKWOmsmUjsO7ZIO4hdkAnwgTD7E3J5C5aXSDEYlfCDGDVk9eo7P5RrW6WtQqJ4i7PqOcz93fvy1wxy/Yyui9kt4FSf0EzO8YU1669Pea3YnxetEvZxfvs54lzMNMe3ZxNACTpdAfyOpeBB56lrGbCjHmvAbqY84e5wF1L4qQ="

# if sealedsecret disabled pass a base 64 url to the mongodb
# db_url: bW9uZ29kYjovL3Jvb3Q6cm9vdEBtb25nby1tb25nb2RiLWhlYWRsZXNz
db_url: ""

# mongo db Values must be declared so the apllication will be connect to the db
mongodb:
  # FullnameOverride is the prefix for all services and resources that will be created by the mongo sub-chart
  fullnameOverride: "mongo-mongodb"
  auth:
    # Database credenditals 
    #rootUser: root
    #rootPassword: "root"
    # Existing secret name with MongoDB(&reg;) credentials (keys: `mongodb-passwords`, `mongodb-root-password`, `mongodb-metrics-password`, ` mongodb-replica-set-key`)
    existingSecret: "dbcred"
  persistence:
    size: 2Gi

# Configuration about ingress
ingress:
  enabled: true 
  # tls means wether to deploy with a tls certificate or not
  tls: false
  # host is the dns for the ingress
  host: elior-crm.ddns.net 

# Configuration about kibana dashboard:
kibana:
  # enable the job to load kibana dashboard
  enabled: true
  # make sure it exists in the logging namespace
  serviceName: elastic-search-kibana
  port: 5601




#Requests and limits for deployment
resources:
  requests:
    memory: "16Mi"
    cpu: "125m"
  limits:
    memory: "128Mi"
    cpu: "500m"

