apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret
spec:
  destination:
    name: ''
    namespace: sealed-secrets
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets/'
    targetRevision: 2.7.3
    chart: sealed-secrets
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
