apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingressnginx
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.4.2
    chart: ingress-nginx
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
