apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/cert-manager
    repoURL: 'https://github.com/PhantomPixelist/protfolio_gitops' # Change to ssh
    # repoURL: 'git@github.com:elior7557/protfolio_gitops.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
