{{- if .Values.ingress.tls }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    {{- if .Values.ingress.staging }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end  }}
    email: elior1001@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
    # - http01:
    #    ingress:
    #      class: nginx
    # testing dns01
    - dns01:
      cloudDNS:
        project: mythic-delight-377411
{{- end }}
