apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | quote }}
  labels:
    app: {{ .Values.name | quote }}
spec:
  replicas: {{ .Values.replicas  }}
  selector:
    matchLabels:
      app: {{ .Values.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.name | quote }}
    spec:
      containers:
      - name: {{ .Values.name | quote }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.port }}
        env:
        - name: DB_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: appsecret
              key: DB_URL
        resources:
{{ toYaml .Values.resources | indent 10 }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}

         

