{{- if .Values.sealedsecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAJvVp32GN4qFEE52FeS8uhZFN/gwjYcZ7kJJGfUtEfh8Env8ouvsBD66Fu5ZzpCgS8KzdGNhKMDUTgJLqqQzShMRpx+hFlE9ZZ6mQj5CNPVTQVwrwDFVYAAhbtTehOpslogL7ysQs8jYOzTMrOLpjBALYW+6YaKDmQKyAVG3/Cn38qeSWiwnRSGubwG5XhFNT827woX9NAbfUocaMiwXVHd4nXyU44ArFQzWPf1DIzypWGy/ponXDgVnd9tU9UNQqiNIk8Hfuzmv4bZdNRt6VYFsqtgya4Zhp69U0VrW7H5SXhWqnPTlC8h6N392jEsY24WDqPUUd3Ez4THNSh0nKhHAvZjVJoL0nY5xFTXW8HlffAjDBkQsfjMuuFhWRnRlnQLfmzOI99EV6PH5sE+huNKupW4dno3KMVt9lSaPJt+Tsn1nyDTwQIgo9xLUbuALqE84x4CRdYLRJC9eQ77J48f+udd1aLJ41FYRXzzJ+zHBu7ZyUsRz5/eluzSdThF+HQmh3gz2hoaa0cGal3FTjLLw22aAidVKW1T18vn+/1AIDTv8Y9CDjBgX2HVlR7THJBZbESGMduuxOxglyboYRGyfCVxSQucxFGw7wsx16bgQMg6y4AK12XUpzftGyVnPIRgAmpNkfCJVsL3/DRLGCKtmrO8n68H4NOKAO6/Yubbs5R09TKldRthjWY3q06WzmEozk9t9wzFJ6P1glAJX30rPXdL9c1Ao11a/yJOAO1DGGs8s2h9bDHGk9YvdwkmQegCvTQwm9Mp989UCZL3+dvDyLDT3WN9Kam9Z48kwAebOZn8FN/AUcpSpoEakpTmAZnHDYXE2Bw
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
{{- end }}
