{{- if .Values.sealedsecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    DB_URL: {{ .Values.sealedsecret.db_url }}
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
{{- end }}
