apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | quote }}
spec:
  selector:
    app: {{ .Values.name | quote }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}
