# Use an existing secret for the admin user.
admin:
  ## Name of the secret. Can be templated.
  existingSecret: "grafanacred"
  userKey: user
  passwordKey: password

## promethus data source in grafaba
datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://prometheus-server
     access: proxy
     isDefault: true

dashboards:
  default:
    local-dashboard-gitlab:
      url: https://github.com/rfmoz/grafana-dashboards/blob/master/prometheus/node-exporter-full.json