# Use an existing secret for the admin user.
admin:
  ## Name of the secret. Can be templated.
  existingSecret: "grafanacred"
  userKey: user
  passwordKey: password

## promethus data source in grafaba
datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://prometheus-server
     access: proxy
     isDefault: true

## Importing custom dashboards
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: default
      orgId: 1
      folder: ""
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

# node exporter
dashboards:
  default:
    nodeExporter-dashboard:
      file: dashboards/nodeExporter-dashboard.json
    ingressnginx-dashboard:
      file: dashboards/ingress-dashboard.json
    Alert-Dashboard:
      file: dashboards/alert-dashboards.json

notifiers:
  - name: slack-alerts-channel
    type: slack
    uid: 8oIQIA14k
    # either
    org_id: 2
    # # or
    # org_name: Main Org.
    is_default: true
    send_reminder: true
    frequency: 1h
    disable_resolve_message: false
    # See `Supported Settings` section for settings supporter for each
    # alert notification type.
    settings:
      url: https://hooks.slack.com/services/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


# notifiers: {}
#  notifiers.yaml:
#    notifiers:
#    - name: email-notifier
#      type: email
#      uid: email1
#      # either:
#      org_id: 1
#      # or
#      org_name: Main Org.
#      is_default: true
#      settings:
#        addresses: an_email_address@example.com
#    delete_notifiers:




# - uid: JEVdi01Vz
#   name: slack-alerts-channel
#   type: slack
#   settings:
#     url: "[REDACTED]"
#   disableResolveMessage: false

      
# dashboards:
#   default:
#     nodeExporter-dashboard2:
#       gnetId: 1860
#       datasource: Prometheus

# dashboards:
#   default:
#     nodeExporter-dashboard2:
#       gnetId: 15172
#       datasource: Prometheus




# dashboards:
#   default:
#     nodeExporter-dashboard:
#       gnetId: 405
#       datasource: Prometheus


# dashboards:
#   default:
#     nodeExporter-dashboard:
#       file: dashboards/nodeExporter-dashboard.json